### PR TITLE
Resolves Black Screen

### PR DESCRIPTION
**Pull request by wilfriedE**
#12 Merged the current changes with the fix for Black screen.

The issue that remains right now is that none of the buttons work.

### CODE REVIEW

**Comment by justwheel** [comment]
@wilfriedE Does this PR have the same changes as [tcreeds#14](https://github.com/tcreeds/PyCut/pull/14)?

**Comment by wilfriedE** [comment]
@jflory7 yes, it's the same changes in addition to the current changes on FOSSRIT/PyCut Master. I'll close the PR On tcreeds's fork.

**Comment by justwheel** [comment]
@wilfriedE I'm going to trust your best judgment here. If you think it's good to merge, feel free to go ahead and bring it into the repository.

**Comment by ghost** [comment]
On Fri, Jan 20, 2017 at 03:51:36PM -0800, Justin W. Flory wrote:
> @wilfriedE I'm going to trust your best judgment here. If you think it's good
> to merge, feel free to go ahead and bring it into the repository.

Not sure if @wilfriedE has had access to an XO recently, but if not, and if
he wants to try this out on one during upcoming FOSS hours (same time as
last semester) I'm sure we could get that worked out and it would be useful
and reassuring.

-- 
Joe

**Comment by wilfriedE** [comment]
@jflory7 I think on top of the current changes, it's good to push as it provides a fix. However. would prefer to wait for a fix on the button issues before another release.

**Comment by wilfriedE** [comment]
@ritjoe I'll plan on stoping by to test it on an actual XO. I was able to run Sugar on a vm and test it there.

**Pull request merged**
